# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('spending', models.CharField(choices=[('0', '$0 - $25'), ('25', '$25 - $50'), ('50', '$50 - $100'), ('100', '$100+')], default='Unspecified', max_length=2, verbose_name='Please choose your spending at the shopping area you have visited')),
                ('area', models.ForeignKey(default='Unspecified', on_delete=django.db.models.deletion.CASCADE, to='mainsite.Area', verbose_name='Please choose your Area')),
                ('shop', models.ForeignKey(default='Unspecified', on_delete=django.db.models.deletion.CASCADE, to='mainsite.Shop', verbose_name='Please choose your Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('traveller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainsite.Traveller')),
                ('status', models.CharField(choices=[('S', 'Students'), ('E', 'Employed'), ('N', 'Not currently employed'), ('R', 'Retired'), ('O', 'Other')], default='Unspecified', max_length=1, verbose_name='What is your status?')),
                ('other_status', models.CharField(blank=True, max_length=50)),
                ('age', models.CharField(choices=[('1', '1 - 25'), ('2', '26 - 35'), ('3', '36 - 50'), ('5', '51+')], default='Unspecified', max_length=1, verbose_name='Which age group are you in?')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'I prefer not to specify')], default='Unspecified', max_length=1, verbose_name='Your Gender:')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('traveller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainsite.Traveller')),
                ('purpose', models.CharField(choices=[('L', 'Leisure'), ('B', 'Business'), ('O', 'Other')], default='Unspecified', max_length=1, verbose_name='What is the purpose for this air trip?')),
                ('other_purpose', models.CharField(blank=True, max_length=50)),
                ('group', models.CharField(choices=[('G', 'Group'), ('S', 'Self-planned')], default='Unspecified', max_length=1, verbose_name='Are you in an organized traveling group or self-planned traveler?')),
                ('group_number', models.CharField(choices=[('0', 'Travel alone'), ('1', '1-2'), ('3', '3-4'), ('5', '5-10'), ('11', '11+')], default='Unspecified', max_length=2, verbose_name='How many people are you traveling with?')),
                ('time_period', models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening'), ('L', 'Late Night')], default='Unspecified', max_length=2, verbose_name='During which time period will your flight depart from Pittsburgh International Airport?')),
                ('how_often', models.CharField(choices=[('W', 'Once a Week'), ('M', 'Once a Month'), ('HY', 'Once every 6 months'), ('LY', 'Less often than once a year'), ('Y', 'Once a year')], default='Unspecified', max_length=2, verbose_name='How often do you fly from Pittsburgh International Airport?')),
                ('airline', models.CharField(choices=[('AC', 'Air Canada'), ('AL', 'Allegiant'), ('AA', 'American Airlines'), ('CO', 'Condor'), ('DA', 'Delta Air Lines'), ('JB', 'JetBlue'), ('FR', 'Frontier'), ('OJ', 'OneJet'), ('PO', 'Porter'), ('SW', 'Southwest'), ('SA', 'Southern Airways Express'), ('UA', 'United Airlines'), ('WO', 'WOW'), ('O', 'other')], max_length=2, verbose_name='What airline are you traveling on?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='shopactivity',
            name='traveller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Traveller'),
        ),
    ]
