# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopactivity',
            name='traveller',
            field=models.ForeignKey(default='Unspecified', on_delete=django.db.models.deletion.CASCADE, to='mainsite.Traveller'),
        ),
    ]
