# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'I prefer not to specify')], default='Unspecified', max_length=1, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
    ]
