# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 17:52
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20170401_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='status',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('S', 'Students'), ('E', 'Employed'), ('N', 'Not currently employed'), ('R', 'Retired'), ('O', 'Other')], default=1, max_length=1, verbose_name='What is your status?'),
            preserve_default=False,
        ),
    ]
