# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0002_auto_20170402_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportActivity',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('traveller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainsite.Traveller')),
                ('leisure_time', models.CharField(choices=[('0', '< 30min'), ('0.5', '30min - 1h'), ('1', '1h - 2h'), ('2', '2h +')], default='Unspecified', max_length=3, verbose_name='How much leisure time do you have before boarding?')),
                ('shopping_spending', models.CharField(choices=[('-1', "I didn't visit this place."), ('0', '$0'), ('1', '$0 - $25'), ('25', '$25 - $50'), ('50', '$50 - $100'), ('100', '$100+')], default='Unspecified', max_length=3, verbose_name='Shopping')),
                ('coffee_shop_spending', models.CharField(choices=[('-1', "I didn't visit this place."), ('0', '$0'), ('1', '$0 - $25'), ('25', '$25 - $50'), ('50', '$50 - $100'), ('100', '$100+')], default='Unspecified', max_length=3, verbose_name='Coffee Shop')),
                ('bar_spending', models.CharField(choices=[('-1', "I didn't visit this place."), ('0', '$0'), ('1', '$0 - $25'), ('25', '$25 - $50'), ('50', '$50 - $100'), ('100', '$100+')], default='Unspecified', max_length=3, verbose_name='Bar/Dining')),
                ('news_spending', models.CharField(choices=[('-1', "I didn't visit this place."), ('0', '$0'), ('1', '$0 - $25'), ('25', '$25 - $50'), ('50', '$50 - $100'), ('100', '$100+')], default='Unspecified', max_length=3, verbose_name='News/Gift/Book Shop')),
                ('kidsport_spending', models.CharField(choices=[('-1', "I didn't visit this place."), ('0', '$0'), ('1', '$0 - $25'), ('25', '$25 - $50'), ('50', '$50 - $100'), ('100', '$100+')], default='Unspecified', max_length=3, verbose_name="KidsPort (Children's Play Area)")),
                ('other_spending', models.CharField(choices=[('-1', "I didn't visit this place."), ('0', '$0'), ('1', '$0 - $25'), ('25', '$25 - $50'), ('50', '$50 - $100'), ('100', '$100+')], default='Unspecified', max_length=3, verbose_name='Other')),
                ('other_name', models.CharField(blank=True, default='Unspecified', max_length=50, verbose_name='If you choose "other" in the places you have visited, please specify')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='shopactivity',
            name='spending',
            field=models.CharField(choices=[('0', '$0 - $25'), ('25', '$25 - $50'), ('50', '$50 - $100'), ('100', '$100+')], default='Unspecified', max_length=3, verbose_name='Please choose your spending at the shopping area you have visited'),
        ),
    ]
