# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_auto_20170403_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportactivity',
            name='other_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='If you choose "other" in the places you have visited, please specify'),
        ),
    ]
