# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0003_background_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='background',
            name='status',
            field=models.CharField(choices=[('S', 'Students'), ('E', 'Employed'), ('N', 'Not currently employed'), ('R', 'Retired'), ('O', 'Other')], max_length=1, verbose_name='What is your status?'),
        ),
        migrations.AlterField(
            model_name='background',
            name='traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Traveller', unique=True),
        ),
    ]
