# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0004_auto_20170401_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='id',
        ),
        migrations.AlterField(
            model_name='background',
            name='traveller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainsite.Traveller'),
        ),
    ]
