# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20170401_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='age',
            field=models.CharField(choices=[('1', '1 - 25'), ('2', '26 - 35'), ('3', '36 - 50'), ('5', '51+')], default='Unspecified', max_length=1, verbose_name='Which age group are you in?'),
        ),
        migrations.AlterField(
            model_name='background',
            name='status',
            field=models.CharField(choices=[('S', 'Students'), ('E', 'Employed'), ('N', 'Not currently employed'), ('R', 'Retired'), ('O', 'Other')], default='Unspecified', max_length=1, verbose_name='What is your status?'),
        ),
    ]
