# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20170401_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('traveller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainsite.Traveller')),
                ('purpose', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
