# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_travelplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='other_purpose',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='purpose',
            field=models.CharField(choices=[('L', 'Leisure'), ('B', 'Business'), ('O', 'Other')], default='Unspecified', max_length=1, verbose_name='What is the purpose for this air trip?'),
        ),
    ]
