# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 19:53
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0007_auto_20170403_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportactivity',
            name='will_visit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A', 'Shopping (Apparels, Cosmetics, duty-free etc.)'), ('B', 'Coffee Shop'), ('C', 'Bar/Dining'), ('D', 'News/Gift/Book Shop'), ('E', 'Convenience Store'), ('F', 'Vending Machine'), ('G', "KidsPort (Children's Play Area)"), ('H', '24*7 Grocery Store'), ('I', 'Other')], max_length=3, verbose_name='Where would you like to visit if you have enough time? Please choose your top 3 preferences.'),
        ),
    ]
