# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-04 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20170403_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportactivity',
            name='will_visit',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A', 'Shopping (Apparels, Cosmetics, duty-free etc.)'), ('B', 'Coffee Shop'), ('C', 'Bar/Dining'), ('D', 'News/Gift/Book Shop'), ('E', 'Convenience Store'), ('F', 'Vending Machine'), ('G', "KidsPort (Children's Play Area)"), ('H', '24*7 Grocery Store'), ('I', 'Other')], max_length=10, verbose_name='Where would you like to visit if you have enough time? Please choose your top 3 preferences.'),
        ),
        migrations.AlterField(
            model_name='shopactivity',
            name='area',
            field=models.ForeignKey(default='Unspecified', on_delete=django.db.models.deletion.CASCADE, to='mainsite.Area', verbose_name='Please select your current location'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='airline',
            field=models.CharField(choices=[('AC', 'Air Canada'), ('AL', 'Allegiant'), ('AA', 'American Airlines'), ('CO', 'Condor'), ('DA', 'Delta Air Lines'), ('JB', 'JetBlue'), ('FR', 'Frontier'), ('OJ', 'OneJet'), ('PO', 'Porter'), ('SP', 'Spirit'), ('SW', 'Southwest'), ('SA', 'Southern Airways Express'), ('UA', 'United Airlines'), ('WO', 'WOW'), ('O', 'other')], max_length=2, verbose_name='What airline are you traveling on?'),
        ),
    ]
