# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0009_auto_20170401_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='other_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='background',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'I prefer not to specify')], default='Unspecified', max_length=1, verbose_name='Your Gender:'),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='other_purpose',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
    ]
