# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 23:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_auto_20170401_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='airline',
            field=models.CharField(choices=[('AC', 'Air Canada'), ('AL', 'Allegiant'), ('AA', 'American Airlines'), ('CO', 'Condor'), ('DA', 'Delta Air Lines'), ('JB', 'JetBlue'), ('FR', 'Frontier'), ('OJ', 'OneJet'), ('PO', 'Porter'), ('SW', 'Southwest'), ('SA', 'Southern Airways Express'), ('UA', 'United Airlines'), ('WO', 'WOW'), ('O', 'other')], default='Unspecified', max_length=2, verbose_name='What airline are you traveling on?'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='group',
            field=models.CharField(choices=[('G', 'Group'), ('S', 'Self-planned')], default='Unspecified', max_length=1, verbose_name='Are you in an organized traveling group or self-planned traveler?'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='group_number',
            field=models.CharField(choices=[('0', 'Travel alone'), ('1', '1-2'), ('3', '3-4'), ('5', '5-10'), ('11', '11+')], default='Unspecified', max_length=2, verbose_name='How many people are you traveling with?'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='how_often',
            field=models.CharField(choices=[('W', 'Once a Week'), ('M', 'Once a Month'), ('HY', 'Once every 6 months'), ('LY', 'Less often than once a year'), ('Y', 'Once a year')], default='Unspecified', max_length=2, verbose_name='How often do you fly from Pittsburgh International Airport?'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='time_period',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening'), ('L', 'Late Night')], default='Unspecified', max_length=2, verbose_name='During which time period will your flight depart from Pittsburgh International Airport?'),
        ),
    ]
