# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0013_remove_travelplan_other_airline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(max_length=50, verbose_name='Area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('shop', models.CharField(max_length=50, verbose_name='Shop')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopActivity',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('traveller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='mainsite.Traveller')),
                ('spending', models.CharField(choices=[('0', '$0 - $25'), ('25', '$25 - $50'), ('50', '$50 - $100'), ('100', '$100+')], default='Unspecified', max_length=2, verbose_name='Please choose your spending at the shopping area you have visited.')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Area')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.Shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='airline',
            field=models.CharField(choices=[('AC', 'Air Canada'), ('AL', 'Allegiant'), ('AA', 'American Airlines'), ('CO', 'Condor'), ('DA', 'Delta Air Lines'), ('JB', 'JetBlue'), ('FR', 'Frontier'), ('OJ', 'OneJet'), ('PO', 'Porter'), ('SW', 'Southwest'), ('SA', 'Southern Airways Express'), ('UA', 'United Airlines'), ('WO', 'WOW'), ('O', 'other')], max_length=2, verbose_name='What airline are you traveling on?'),
        ),
    ]
