# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 02:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0014_auto_20170402_0202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='area',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='shop',
            new_name='name',
        ),
    ]
